apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  AZURE_STORAGE_CONTAINER_ENCOUNTER_MEDIA: {{ .Values.env.AZURE_STORAGE_CONTAINER_ENCOUNTER_MEDIA | quote }}
